# Generated by Django 5.2.5 on 2025-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='miles_driven',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='multimedia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
